[book]
authors = ["pradi-dev"]
language = "en"
src = "src"
title = "UMSP — Unified Messaging & Social Protocol"
description = "Specification for a federated protocol unifying direct messaging, Discord-style servers, rich chat, and social feeds."

[output.html]
git-repository-url = "https://github.com/pradi-dev/umsp-spec"
edit-url-template = "https://github.com/pradi-dev/umsp-spec/edit/main/{path}"
default-theme = "light"
preferred-dark-theme = "navy"

[output.html.fold]
enable = true
level = 1
